SERVER=src.UDPServer
PORT_ORIGIN=6666
PORT_DESTIN=5555
IP_ADDRESS=127.0.0.1
NICKNAME=server2

echo "Running $NICKNAME in $IP_ADDRESS:$PORT_ORIGIN"
java $SERVER $PORT_ORIGIN $PORT_DESTIN $NICKNAME $IP_ADDRESS